Repository annahinnyc/code4good-accessibility, pull requests merged in 2020-04, with the labels that each got.

#35 Update Pull_request_template.md
  .github/pull_request_template.md
Labels: enhancement

#36 Add actions for review and label
  .github/auto-label.json
  .github/auto_assign.yml
  .github/pull_request_template.md
  .github/workflows/auto_assign_approved_label.yml
  .github/workflows/auto_assign_reviewer_action.yml
  .github/workflows/auto_pull_request_label_action.yml
Labels: Read-To-Review

#41 Update check-file-name.yml to run for PR instead of just `on push`
  .github/workflows/check-file-name.yml
Labels: Read-To-Review

#40 audit results for C4G-18
  public/scan-results/data/C4G-18_IN_10.json
  public/scan-results/data/C4G-18_IN_11.json
  public/scan-results/data/C4G-18_IN_12.json
  public/scan-results/data/C4G-18_IN_13.json
  public/scan-results/data/C4G-18_IN_14.json
  public/scan-results/data/C4G-18_IN_15.json
  public/scan-results/data/C4G-18_IN_16.json
  public/scan-results/data/C4G-18_IN_17.json
  public/scan-results/data/C4G-18_IN_18.json
  public/scan-results/data/C4G-18_IN_19.json
  public/scan-results/data/C4G-18_IN_2.json
  public/scan-results/data/C4G-18_IN_20.json
  public/scan-results/data/C4G-18_IN_21.json
  public/scan-results/data/C4G-18_IN_22.json
  public/scan-results/data/C4G-18_IN_23.json
  public/scan-results/data/C4G-18_IN_24.json
  public/scan-results/data/C4G-18_IN_25.json
  public/scan-results/data/C4G-18_IN_26.json
  public/scan-results/data/C4G-18_IN_27.json
  public/scan-results/data/C4G-18_IN_28.json
  public/scan-results/data/C4G-18_IN_29.json
  public/scan-results/data/C4G-18_IN_3.json
  public/scan-results/data/C4G-18_IN_30.json
  public/scan-results/data/C4G-18_IN_31.json
  public/scan-results/data/C4G-18_IN_32.json
  public/scan-results/data/C4G-18_IN_33.json
  public/scan-results/data/C4G-18_IN_34.json
  public/scan-results/data/C4G-18_IN_35.json
  public/scan-results/data/C4G-18_IN_36.json
  public/scan-results/data/C4G-18_IN_37.json
  public/scan-results/data/C4G-18_IN_38.json
  public/scan-results/data/C4G-18_IN_39.json
  public/scan-results/data/C4G-18_IN_4.json
  public/scan-results/data/C4G-18_IN_40.json
  public/scan-results/data/C4G-18_IN_41.json
  public/scan-results/data/C4G-18_IN_42.json
  public/scan-results/data/C4G-18_IN_43.json
  public/scan-results/data/C4G-18_IN_44.json
  public/scan-results/data/C4G-18_IN_45.json
  public/scan-results/data/C4G-18_IN_46.json
  public/scan-results/data/C4G-18_IN_47.json
  public/scan-results/data/C4G-18_IN_48.json
  public/scan-results/data/C4G-18_IN_49.json
  public/scan-results/data/C4G-18_IN_5.json
  public/scan-results/data/C4G-18_IN_50.json
  public/scan-results/data/C4G-18_IN_51.json
  public/scan-results/data/C4G-18_IN_6.json
  public/scan-results/data/C4G-18_IN_7.json
  public/scan-results/data/C4G-18_IN_8.json
  public/scan-results/data/C4G-18_IN_9.json
  public/tools/auto-audit/auto-audit.py
Labels: Approved

#48 C4G-30 audits
  public/scan-results/data/C4G-30_CD_1.json
  public/scan-results/data/C4G-30_CD_10.json
  public/scan-results/data/C4G-30_CD_11.json
  public/scan-results/data/C4G-30_CD_12.json
  public/scan-results/data/C4G-30_CD_13.json
  public/scan-results/data/C4G-30_CD_14.json
  public/scan-results/data/C4G-30_CD_15.json
  public/scan-results/data/C4G-30_CD_16.json
  public/scan-results/data/C4G-30_CD_17.json
  public/scan-results/data/C4G-30_CD_18.json
  public/scan-results/data/C4G-30_CD_19.json
  public/scan-results/data/C4G-30_CD_2.json
  public/scan-results/data/C4G-30_CD_20.json
  public/scan-results/data/C4G-30_CD_21.json
  public/scan-results/data/C4G-30_CD_22.json
  public/scan-results/data/C4G-30_CD_23.json
  public/scan-results/data/C4G-30_CD_24.json
  public/scan-results/data/C4G-30_CD_25.json
  public/scan-results/data/C4G-30_CD_26.json
  public/scan-results/data/C4G-30_CD_27.json
  public/scan-results/data/C4G-30_CD_28.json
  public/scan-results/data/C4G-30_CD_29.json
  public/scan-results/data/C4G-30_CD_3.json
  public/scan-results/data/C4G-30_CD_30.json
  public/scan-results/data/C4G-30_CD_31.json
  public/scan-results/data/C4G-30_CD_32.json
  public/scan-results/data/C4G-30_CD_33.json
  public/scan-results/data/C4G-30_CD_34.json
  public/scan-results/data/C4G-30_CD_35.json
  public/scan-results/data/C4G-30_CD_36.json
  public/scan-results/data/C4G-30_CD_37.json
  public/scan-results/data/C4G-30_CD_38.json
  public/scan-results/data/C4G-30_CD_39.json
  public/scan-results/data/C4G-30_CD_4.json
  public/scan-results/data/C4G-30_CD_40.json
  public/scan-results/data/C4G-30_CD_41.json
  public/scan-results/data/C4G-30_CD_42.json
  public/scan-results/data/C4G-30_CD_43.json
  public/scan-results/data/C4G-30_CD_44.json
  public/scan-results/data/C4G-30_CD_45.json
  public/scan-results/data/C4G-30_CD_46.json
  public/scan-results/data/C4G-30_CD_47.json
  public/scan-results/data/C4G-30_CD_48.json
  public/scan-results/data/C4G-30_CD_49.json
  public/scan-results/data/C4G-30_CD_5.json
  public/scan-results/data/C4G-30_CD_50.json
  public/scan-results/data/C4G-30_CD_6.json
  public/scan-results/data/C4G-30_CD_7.json
  public/scan-results/data/C4G-30_CD_8.json
  public/scan-results/data/C4G-30_CD_9.json
Labels: Approved

#47 C4G-29_CD audits
  public/scan-results/data/C4G-29_CD_1.json
  public/scan-results/data/C4G-29_CD_10.json
  public/scan-results/data/C4G-29_CD_11.json
  public/scan-results/data/C4G-29_CD_12.json
  public/scan-results/data/C4G-29_CD_13.json
  public/scan-results/data/C4G-29_CD_14.json
  public/scan-results/data/C4G-29_CD_15.json
  public/scan-results/data/C4G-29_CD_16.json
  public/scan-results/data/C4G-29_CD_17.json
  public/scan-results/data/C4G-29_CD_18.json
  public/scan-results/data/C4G-29_CD_19.json
  public/scan-results/data/C4G-29_CD_2.json
  public/scan-results/data/C4G-29_CD_20.json
  public/scan-results/data/C4G-29_CD_21.json
  public/scan-results/data/C4G-29_CD_22.json
  public/scan-results/data/C4G-29_CD_23.json
  public/scan-results/data/C4G-29_CD_24.json
  public/scan-results/data/C4G-29_CD_25.json
  public/scan-results/data/C4G-29_CD_26.json
  public/scan-results/data/C4G-29_CD_27.json
  public/scan-results/data/C4G-29_CD_28.json
  public/scan-results/data/C4G-29_CD_29.json
  public/scan-results/data/C4G-29_CD_3.json
  public/scan-results/data/C4G-29_CD_30.json
  public/scan-results/data/C4G-29_CD_31.json
  public/scan-results/data/C4G-29_CD_32.json
  public/scan-results/data/C4G-29_CD_33.json
  public/scan-results/data/C4G-29_CD_34.json
  public/scan-results/data/C4G-29_CD_35.json
  public/scan-results/data/C4G-29_CD_36.json
  public/scan-results/data/C4G-29_CD_37.json
  public/scan-results/data/C4G-29_CD_38.json
  public/scan-results/data/C4G-29_CD_39.json
  public/scan-results/data/C4G-29_CD_4.json
  public/scan-results/data/C4G-29_CD_40.json
  public/scan-results/data/C4G-29_CD_41.json
  public/scan-results/data/C4G-29_CD_42.json
  public/scan-results/data/C4G-29_CD_43.json
  public/scan-results/data/C4G-29_CD_44.json
  public/scan-results/data/C4G-29_CD_45.json
  public/scan-results/data/C4G-29_CD_46.json
  public/scan-results/data/C4G-29_CD_47.json
  public/scan-results/data/C4G-29_CD_48.json
  public/scan-results/data/C4G-29_CD_49.json
  public/scan-results/data/C4G-29_CD_5.json
  public/scan-results/data/C4G-29_CD_50.json
  public/scan-results/data/C4G-29_CD_6.json
  public/scan-results/data/C4G-29_CD_7.json
  public/scan-results/data/C4G-29_CD_8.json
  public/scan-results/data/C4G-29_CD_9.json
Labels: Approved
